// Schema parity: schema/sequentdraw.schema.json (draft 2020-12, via
// ajv/dist/2020, devDependency only -- see package.json/CREDITS.md) must
// agree with validateDoc() on every case this schema CAN express, and must
// accept every "cross-reference" case that only validateDoc() can catch
// (documented in the schema's own root `description`).
//
// Corpus lives in tests/fixtures/schema/ (regenerated by
// scripts/gen-schema-fixtures.js):
//   - *-valid.json            both must accept
//   - structural-*.json       both must reject (types/enums/lengths/
//                              structure/the suggested-rationale rule/
//                              the condition-requires-dashed rule, all of
//                              which the schema CAN express)
//   - crossref-*.json         the schema must accept (structurally sound)
//                              but validateDoc() must reject with a
//                              specific code (a rule the schema cannot
//                              express: id references, orphan nodes,
//                              sublabel word count, duplicate ids, etc.)

const { test, describe } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const Ajv = require('ajv/dist/2020');

const { validateDoc, ValidationError } = require('../src/n8n/validate');

const SCHEMA_PATH = path.join(__dirname, '..', 'schema', 'sequentdraw.schema.json');
const FIXTURES_DIR = path.join(__dirname, 'fixtures', 'schema');
const MEDUSA_PATH = path.join(__dirname, '..', 'examples', 'medusa-return-flow.json');

const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
const ajv = new Ajv({ allErrors: true, strict: true });
const ajvValidate = ajv.compile(schema);

function loadFixture(name) {
  return JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, name), 'utf8'));
}

function listFixtures(prefix) {
  return fs
    .readdirSync(FIXTURES_DIR)
    .filter(f => f.startsWith(prefix) && f.endsWith('.json'))
    .sort();
}

// Expected validateDoc() codes for the cross-reference-only fixtures --
// the exact reason validateDoc rejects a schema-valid document.
const CROSSREF_EXPECTED_CODE = {
  'crossref-edge-references-unknown-node.json': 'unknown-node',
  'crossref-node-parentid-unknown-group.json': 'unknown-group',
  'crossref-orphan-node.json': 'orphan-node',
  'crossref-sublabel-word-count.json': 'sublabel-too-many-words',
  'crossref-duplicate-node-id.json': 'duplicate-id',
  'crossref-note-attachto-unknown.json': 'unknown-attach-target',
  'crossref-duplicate-tour-order.json': 'duplicate-order',
  'crossref-tour-nodeids-unknown.json': 'unknown-node',
  'crossref-note-id-collides-with-node.json': 'duplicate-id',
  'crossref-whitespace-only-title.json': 'invalid-title',
  'crossref-node-description-whitespace.json': 'invalid-description',
  'crossref-edge-description-whitespace.json': 'invalid-description',
  'crossref-node-link-whitespace.json': 'invalid-link',
  'crossref-node-link-quote.json': 'invalid-link',
};

// ---------------------------------------------------------------------
// The schema file itself
// ---------------------------------------------------------------------

describe('schema/sequentdraw.schema.json', () => {
  test('is draft 2020-12 with the expected $id', () => {
    assert.strictEqual(schema.$schema, 'https://json-schema.org/draft/2020-12/schema');
    assert.strictEqual(schema.$id, 'https://github.com/thestealthyworker/SequentDraw/blob/main/schema/sequentdraw.schema.json');
  });

  test('compiles under ajv strict mode with no warnings thrown', () => {
    assert.strictEqual(typeof ajvValidate, 'function');
  });

  test('every property in the schema and its $defs carries a title and a description', () => {
    const missing = [];
    function walk(node, atPath) {
      if (!node || typeof node !== 'object') return;
      if (node.properties) {
        for (const [key, sub] of Object.entries(node.properties)) {
          const here = `${atPath}/${key}`;
          if (key === '$schema') continue; // documented but not a domain field
          if (!sub.title) missing.push(`${here} missing title`);
          if (!sub.description) missing.push(`${here} missing description`);
          walk(sub, here);
        }
      }
      if (node.items) walk(node.items, `${atPath}[]`);
      if (node.$defs) {
        for (const [key, sub] of Object.entries(node.$defs)) walk(sub, `$defs/${key}`);
      }
    }
    walk(schema, '');
    assert.deepStrictEqual(missing, []);
  });

  test('the root description lists the cross-reference rules it cannot express', () => {
    for (const term of ['parentId', 'edge.from', 'orphan', 'sublabel', 'dashed', 'namespace', 'attachTo', 'order', 'nodeIds']) {
      assert.ok(schema.description.includes(term), `root description should mention "${term}"`);
    }
  });
});

// ---------------------------------------------------------------------
// Valid fixtures: both must accept
// ---------------------------------------------------------------------

describe('valid fixtures: schema and validateDoc agree (both accept)', () => {
  for (const file of listFixtures('')) {
    if (file.startsWith('structural-') || file.startsWith('crossref-')) continue;
    test(`${file} is accepted by both`, () => {
      const doc = loadFixture(file);
      const ajvOk = ajvValidate(doc);
      assert.ok(ajvOk, `ajv should accept ${file}: ${JSON.stringify(ajvValidate.errors)}`);
      assert.doesNotThrow(() => validateDoc(doc), `validateDoc should accept ${file}`);
    });
  }

  test('the Medusa fixture in tests/fixtures/schema matches examples/medusa-return-flow.json', () => {
    const fromExamples = JSON.parse(fs.readFileSync(MEDUSA_PATH, 'utf8'));
    const fromFixtures = loadFixture('medusa-valid.json');
    assert.deepStrictEqual(fromFixtures, fromExamples);
  });
});

// ---------------------------------------------------------------------
// Structural fixtures: schema and validateDoc must agree (both reject)
// ---------------------------------------------------------------------

describe('structural fixtures: schema and validateDoc agree (both reject)', () => {
  const files = listFixtures('structural-');
  test('there are at least 15 invalid fixtures across structural + crossref', () => {
    const allInvalid = listFixtures('structural-').length + listFixtures('crossref-').length;
    assert.ok(allInvalid >= 15, `expected at least 15 invalid fixtures, found ${allInvalid}`);
  });

  for (const file of files) {
    test(`${file}: ajv rejects and validateDoc throws`, () => {
      const doc = loadFixture(file);
      const ajvOk = ajvValidate(doc);
      assert.strictEqual(ajvOk, false, `ajv should reject ${file}`);
      assert.throws(() => validateDoc(doc), ValidationError, `validateDoc should reject ${file}`);
    });
  }
});

// ---------------------------------------------------------------------
// Cross-reference fixtures: schema accepts, validateDoc rejects with the
// specific code that names the rule the schema cannot express.
// ---------------------------------------------------------------------

describe('cross-reference fixtures: schema accepts, validateDoc rejects with the documented code', () => {
  const files = listFixtures('crossref-');

  test('every crossref fixture has an expected code recorded', () => {
    assert.deepStrictEqual(files, Object.keys(CROSSREF_EXPECTED_CODE).sort());
  });

  for (const file of files) {
    test(`${file}: ajv accepts (structurally sound), validateDoc rejects with "${CROSSREF_EXPECTED_CODE[file]}"`, () => {
      const doc = loadFixture(file);
      const ajvOk = ajvValidate(doc);
      assert.strictEqual(ajvOk, true, `ajv should accept ${file} (it is only wrong by a cross-reference rule): ${JSON.stringify(ajvValidate.errors)}`);

      let caught = null;
      try {
        validateDoc(doc);
      } catch (e) {
        caught = e;
      }
      assert.ok(caught instanceof ValidationError, `validateDoc should reject ${file}`);
      const codes = caught.errors.map(e => e.code);
      assert.ok(
        codes.includes(CROSSREF_EXPECTED_CODE[file]),
        `expected code "${CROSSREF_EXPECTED_CODE[file]}" in ${file}, got [${codes.join(', ')}]`,
      );
    });
  }
});
